USE school_database;

INSERT INTO STUDENT VALUES (1,'Jabson', 20, 'male');
INSERT INTO STUDENT VALUES (2,'Oba', 24, 'male');
INSERT INTO STUDENT VALUES (3,'Sammmy', '23', 'male');    

INSERT INTO COURSE VALUES (100,'Java', 'Chibuzor', 25);
INSERT INTO COURSE VALUES (200,'Python', 'Asa', 65);
INSERT INTO COURSE VALUES (300,'Data_base', 'Esther', 30);
INSERT INTO COURSE VALUES (400,'Spingboot', 'Femi', 98); 

INSERT INTO GRADE VALUES (1, 1, 60);
INSERT INTO GRADE VALUES (1, 2, 70);    
INSERT INTO GRADE VALUES (1, 3, 77);
INSERT INTO GRADE VALUES (2, 1, 68);  
INSERT INTO GRADE VALUES (2, 3, 80);
INSERT INTO GRADE VALUES (3, 2, 67);  
INSERT INTO GRADE VALUES (3, 1, 89);
INSERT INTO GRADE VALUES (2, 2, 72);      
INSERT INTO GRADE VALUES (3, 3, 86);